# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-DOM
version:      0.20
version_from: DOM.pm
installdirs:  site
requires:
  ExtUtils::Depends: 0.205
  ExtUtils::PkgConfig: 1.07
  perl: 5.8.0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
no_index:
  dir:
  - examples
