=head1 NAME

Mozilla::DOM::EntityReference

=for object Mozilla::DOM::EntityReference

Mozilla::DOM::EntityReference is a wrapper around an instance of Mozilla's
nsIDOMEntityReference interface. This inherits from
L<Mozilla::DOM::Node|Mozilla::DOM::Node>.

=cut

=head1 CLASS METHODS

=head2 $iid = Mozilla::DOM::EntityReference->B<GetIID>()

Pass this to QueryInterface.

=cut




=head1 METHODS



Some methods defined for Mozilla::DOM::EntityReference::nsIDOMEntityReference are not available in the particular
library versions against which this module was compiled. 


=head1 SEE ALSO

L<Mozilla::DOM>

=head1 COPYRIGHT

Copyright (C) 2005, Scott Lanning

This software is licensed under the LGPL.  See L<Mozilla::DOM> for a full notice.


=cut

