=head1 NAME

Mozilla::DOM::History

=for object Mozilla::DOM::History

Mozilla::DOM::History is a wrapper around an instance of Mozilla's
nsIDOMHistory interface. This class inherits from
L<Supports|Mozilla::DOM::Supports>.



=cut

=head1 CLASS METHODS

=head2 $iid = Mozilla::DOM::History->B<GetIID>()

Pass this to QueryInterface.

=cut




=head1 METHODS

=head2 $history->B<Back>()

=over






=back

=head2 $history->B<Forward>()

=over






=back

=head2 $current = $history->B<GetCurrent>()

=over






=back

=head2 $length = $history->B<GetLength>()

=over






=back

=head2 $next = $history->B<GetNext>()

=over






=back

=head2 $previous = $history->B<GetPrevious>()

=over






=back

=head2 $history->B<Go>($delta)

=over

=over

=item * $aDelta (integer (long)) 

=back






=back

=head2 $retval = $history->B<Item>($index)

=over

=over

=item * $index (integer (long)) 

=back






=back


=head1 SEE ALSO

L<Mozilla::DOM>

=head1 COPYRIGHT

Copyright (C) 2005, Scott Lanning

This software is licensed under the LGPL.  See L<Mozilla::DOM> for a full notice.


=cut

